### ISSUE TITLE
Not working in Catalina

### ISSUE THREAD

**Issue by jaycbrf4** [emin/WebPQuickLook#28]
Just installed and relaunched finder... It tries to work then just defaults to generic Photoshop icon and no preview.

**Comment by bluetardis** [comment]
Safari under Catalina won't work period.  Many issues including incompatibilities with .webp, .ogg, etc.
Been there and tried that.

If you want to to use Catalina then you should try it with Google Chrome/Chromium/Thorium.

If you use Monterey (12.4) then things will work.

An extra bonus is that if you get your iPad fully updated, it will work reasonably well with Safari and FoundryVTT.

**Comment by jaycbrf4** [comment]
Works fine after restart!
