### ISSUE TITLE
No longer works in ~/Library/QuickLook on Yosemite.

### ISSUE THREAD

**Issue by vitorgalvao** [emin/WebPQuickLook#6]
On [homebrew-cask](https://github.com/caskroom/homebrew-cask) we had an [issue](https://github.com/caskroom/homebrew-cask/issues/6448) open recently pertaining to an [alternative](https://github.com/dchest/webp-quicklook) to this plugin. The problem being it no longer (in Yosemite) works when set in `~/Library/QuickLook` (as opposed to `/Library/QuickLook`, where it does work).

After some tests I found this issue, whatever the cause, also affects your plugin, so maybe you and @dchest would be interested in working together on it. So far, every other quicklook plugin I’ve tried seems to be working normally.

**Comment by KingMob** [comment]
FWIW, I can confirm this still happens on El Capitan, too. Installing in /Library works, ~/Library doesn't.

**Comment by vitorgalvao** [comment]
The plugin seems EOL, so closing the issue.
